# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class VideoUploadBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'video': 'str'
    }

    attribute_map = {
        'video': 'video'
    }

    def __init__(self, video=None):  # noqa: E501
        """VideoUploadBody - a model defined in Swagger"""  # noqa: E501
        self._video = None
        self.discriminator = None
        self.video = video

    @property
    def video(self):
        """Gets the video of this VideoUploadBody.  # noqa: E501

        视频文件。 注意：    1. multipart/form-data中的Content-Type都必须以\"video/\"开头，如\"video/mp4\"，否则会报错：\"unsupported content type xxx\"。   2. 该Content-Type不是加在Header中，是加在请求体里面：![如图](http://p3.pstatp.com/origin/2dd390008887d044455b9)   # noqa: E501

        :return: The video of this VideoUploadBody.  # noqa: E501
        :rtype: str
        """
        return self._video

    @video.setter
    def video(self, video):
        """Sets the video of this VideoUploadBody.

        视频文件。 注意：    1. multipart/form-data中的Content-Type都必须以\"video/\"开头，如\"video/mp4\"，否则会报错：\"unsupported content type xxx\"。   2. 该Content-Type不是加在Header中，是加在请求体里面：![如图](http://p3.pstatp.com/origin/2dd390008887d044455b9)   # noqa: E501

        :param video: The video of this VideoUploadBody.  # noqa: E501
        :type: str
        """
        if video is None:
            raise ValueError("Invalid value for `video`, must not be `None`")  # noqa: E501

        self._video = video

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VideoUploadBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoUploadBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
