# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class OauthClientTokenResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_code': 'ErrorCode',
        'description': 'Description',
        'access_token': 'str',
        'expires_in': 'int'
    }

    attribute_map = {
        'error_code': 'error_code',
        'description': 'description',
        'access_token': 'access_token',
        'expires_in': 'expires_in'
    }

    def __init__(self, error_code=None, description=None, access_token=None, expires_in=None):  # noqa: E501
        """OauthClientTokenResponseData - a model defined in Swagger"""  # noqa: E501
        self._error_code = None
        self._description = None
        self._access_token = None
        self._expires_in = None
        self.discriminator = None
        if error_code is not None:
            self.error_code = error_code
        if description is not None:
            self.description = description
        if access_token is not None:
            self.access_token = access_token
        if expires_in is not None:
            self.expires_in = expires_in

    @property
    def error_code(self):
        """Gets the error_code of this OauthClientTokenResponseData.  # noqa: E501


        :return: The error_code of this OauthClientTokenResponseData.  # noqa: E501
        :rtype: ErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this OauthClientTokenResponseData.


        :param error_code: The error_code of this OauthClientTokenResponseData.  # noqa: E501
        :type: ErrorCode
        """

        self._error_code = error_code

    @property
    def description(self):
        """Gets the description of this OauthClientTokenResponseData.  # noqa: E501


        :return: The description of this OauthClientTokenResponseData.  # noqa: E501
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this OauthClientTokenResponseData.


        :param description: The description of this OauthClientTokenResponseData.  # noqa: E501
        :type: Description
        """

        self._description = description

    @property
    def access_token(self):
        """Gets the access_token of this OauthClientTokenResponseData.  # noqa: E501

        接口调用凭证  # noqa: E501

        :return: The access_token of this OauthClientTokenResponseData.  # noqa: E501
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this OauthClientTokenResponseData.

        接口调用凭证  # noqa: E501

        :param access_token: The access_token of this OauthClientTokenResponseData.  # noqa: E501
        :type: str
        """

        self._access_token = access_token

    @property
    def expires_in(self):
        """Gets the expires_in of this OauthClientTokenResponseData.  # noqa: E501

        access_token接口调用凭证超时时间，单位（秒  # noqa: E501

        :return: The expires_in of this OauthClientTokenResponseData.  # noqa: E501
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this OauthClientTokenResponseData.

        access_token接口调用凭证超时时间，单位（秒  # noqa: E501

        :param expires_in: The expires_in of this OauthClientTokenResponseData.  # noqa: E501
        :type: int
        """

        self._expires_in = expires_in

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OauthClientTokenResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OauthClientTokenResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
