# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiExtHotelOrderCommitResponse1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_date': 'str',
        'date_price': 'int'
    }

    attribute_map = {
        '_date': 'date',
        'date_price': 'date_price'
    }

    def __init__(self, _date=None, date_price=None):  # noqa: E501
        """PoiExtHotelOrderCommitResponse1 - a model defined in Swagger"""  # noqa: E501
        self.__date = None
        self._date_price = None
        self.discriminator = None
        self._date = _date
        self.date_price = date_price

    @property
    def _date(self):
        """Gets the _date of this PoiExtHotelOrderCommitResponse1.  # noqa: E501

        入住日期 yyyyMMdd  # noqa: E501

        :return: The _date of this PoiExtHotelOrderCommitResponse1.  # noqa: E501
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this PoiExtHotelOrderCommitResponse1.

        入住日期 yyyyMMdd  # noqa: E501

        :param _date: The _date of this PoiExtHotelOrderCommitResponse1.  # noqa: E501
        :type: str
        """
        if _date is None:
            raise ValueError("Invalid value for `_date`, must not be `None`")  # noqa: E501

        self.__date = _date

    @property
    def date_price(self):
        """Gets the date_price of this PoiExtHotelOrderCommitResponse1.  # noqa: E501

        入住日价格, 人民币分  # noqa: E501

        :return: The date_price of this PoiExtHotelOrderCommitResponse1.  # noqa: E501
        :rtype: int
        """
        return self._date_price

    @date_price.setter
    def date_price(self, date_price):
        """Sets the date_price of this PoiExtHotelOrderCommitResponse1.

        入住日价格, 人民币分  # noqa: E501

        :param date_price: The date_price of this PoiExtHotelOrderCommitResponse1.  # noqa: E501
        :type: int
        """
        if date_price is None:
            raise ValueError("Invalid value for `date_price`, must not be `None`")  # noqa: E501

        self._date_price = date_price

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiExtHotelOrderCommitResponse1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiExtHotelOrderCommitResponse1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
