# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiExtHotelOrderCommitResponse2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_ext_id': 'str',
        'error_code': 'ErrorCode',
        'description': 'Description'
    }

    attribute_map = {
        'order_ext_id': 'order_ext_id',
        'error_code': 'error_code',
        'description': 'description'
    }

    def __init__(self, order_ext_id=None, error_code=None, description=None):  # noqa: E501
        """PoiExtHotelOrderCommitResponse2 - a model defined in Swagger"""  # noqa: E501
        self._order_ext_id = None
        self._error_code = None
        self._description = None
        self.discriminator = None
        self.order_ext_id = order_ext_id
        self.error_code = error_code
        self.description = description

    @property
    def order_ext_id(self):
        """Gets the order_ext_id of this PoiExtHotelOrderCommitResponse2.  # noqa: E501

        外部订单id  # noqa: E501

        :return: The order_ext_id of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :rtype: str
        """
        return self._order_ext_id

    @order_ext_id.setter
    def order_ext_id(self, order_ext_id):
        """Sets the order_ext_id of this PoiExtHotelOrderCommitResponse2.

        外部订单id  # noqa: E501

        :param order_ext_id: The order_ext_id of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :type: str
        """
        if order_ext_id is None:
            raise ValueError("Invalid value for `order_ext_id`, must not be `None`")  # noqa: E501

        self._order_ext_id = order_ext_id

    @property
    def error_code(self):
        """Gets the error_code of this PoiExtHotelOrderCommitResponse2.  # noqa: E501


        :return: The error_code of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :rtype: ErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this PoiExtHotelOrderCommitResponse2.


        :param error_code: The error_code of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :type: ErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def description(self):
        """Gets the description of this PoiExtHotelOrderCommitResponse2.  # noqa: E501


        :return: The description of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PoiExtHotelOrderCommitResponse2.


        :param description: The description of this PoiExtHotelOrderCommitResponse2.  # noqa: E501
        :type: Description
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiExtHotelOrderCommitResponse2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiExtHotelOrderCommitResponse2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
