# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiSupplierSyncServices(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'service_type': 'int',
        'enable': 'int',
        'entry': 'PoiSupplierSyncEntry'
    }

    attribute_map = {
        'service_type': 'service_type',
        'enable': 'enable',
        'entry': 'entry'
    }

    def __init__(self, service_type=None, enable=None, entry=None):  # noqa: E501
        """PoiSupplierSyncServices - a model defined in Swagger"""  # noqa: E501
        self._service_type = None
        self._enable = None
        self._entry = None
        self.discriminator = None
        if service_type is not None:
            self.service_type = service_type
        if enable is not None:
            self.enable = enable
        if entry is not None:
            self.entry = entry

    @property
    def service_type(self):
        """Gets the service_type of this PoiSupplierSyncServices.  # noqa: E501

        服务类型(201-预约点餐服务, 202-预约订位服务, 203-排队取号服务, 9001-门票预订服务, 9101-团购套餐服务)  # noqa: E501

        :return: The service_type of this PoiSupplierSyncServices.  # noqa: E501
        :rtype: int
        """
        return self._service_type

    @service_type.setter
    def service_type(self, service_type):
        """Sets the service_type of this PoiSupplierSyncServices.

        服务类型(201-预约点餐服务, 202-预约订位服务, 203-排队取号服务, 9001-门票预订服务, 9101-团购套餐服务)  # noqa: E501

        :param service_type: The service_type of this PoiSupplierSyncServices.  # noqa: E501
        :type: int
        """
        allowed_values = [201, 202, 203, 9001, 9101]  # noqa: E501
        if service_type not in allowed_values:
            raise ValueError(
                "Invalid value for `service_type` ({0}), must be one of {1}"  # noqa: E501
                .format(service_type, allowed_values)
            )

        self._service_type = service_type

    @property
    def enable(self):
        """Gets the enable of this PoiSupplierSyncServices.  # noqa: E501

        上线状态(1:上线，2:下线)  # noqa: E501

        :return: The enable of this PoiSupplierSyncServices.  # noqa: E501
        :rtype: int
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this PoiSupplierSyncServices.

        上线状态(1:上线，2:下线)  # noqa: E501

        :param enable: The enable of this PoiSupplierSyncServices.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2]  # noqa: E501
        if enable not in allowed_values:
            raise ValueError(
                "Invalid value for `enable` ({0}), must be one of {1}"  # noqa: E501
                .format(enable, allowed_values)
            )

        self._enable = enable

    @property
    def entry(self):
        """Gets the entry of this PoiSupplierSyncServices.  # noqa: E501


        :return: The entry of this PoiSupplierSyncServices.  # noqa: E501
        :rtype: PoiSupplierSyncEntry
        """
        return self._entry

    @entry.setter
    def entry(self, entry):
        """Sets the entry of this PoiSupplierSyncServices.


        :param entry: The entry of this PoiSupplierSyncServices.  # noqa: E501
        :type: PoiSupplierSyncEntry
        """

        self._entry = entry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiSupplierSyncServices, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiSupplierSyncServices):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
