# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiSupplierSyncEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entry_type': 'int',
        'entry_mini_app': 'PoiSupplierSyncEntryResponse'
    }

    attribute_map = {
        'entry_type': 'entry_type',
        'entry_mini_app': 'entry_mini_app'
    }

    def __init__(self, entry_type=None, entry_mini_app=None):  # noqa: E501
        """PoiSupplierSyncEntry - a model defined in Swagger"""  # noqa: E501
        self._entry_type = None
        self._entry_mini_app = None
        self.discriminator = None
        if entry_type is not None:
            self.entry_type = entry_type
        if entry_mini_app is not None:
            self.entry_mini_app = entry_mini_app

    @property
    def entry_type(self):
        """Gets the entry_type of this PoiSupplierSyncEntry.  # noqa: E501

        入口类型(1:H5，2:抖音小程序)  # noqa: E501

        :return: The entry_type of this PoiSupplierSyncEntry.  # noqa: E501
        :rtype: int
        """
        return self._entry_type

    @entry_type.setter
    def entry_type(self, entry_type):
        """Sets the entry_type of this PoiSupplierSyncEntry.

        入口类型(1:H5，2:抖音小程序)  # noqa: E501

        :param entry_type: The entry_type of this PoiSupplierSyncEntry.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2]  # noqa: E501
        if entry_type not in allowed_values:
            raise ValueError(
                "Invalid value for `entry_type` ({0}), must be one of {1}"  # noqa: E501
                .format(entry_type, allowed_values)
            )

        self._entry_type = entry_type

    @property
    def entry_mini_app(self):
        """Gets the entry_mini_app of this PoiSupplierSyncEntry.  # noqa: E501


        :return: The entry_mini_app of this PoiSupplierSyncEntry.  # noqa: E501
        :rtype: PoiSupplierSyncEntryResponse
        """
        return self._entry_mini_app

    @entry_mini_app.setter
    def entry_mini_app(self, entry_mini_app):
        """Sets the entry_mini_app of this PoiSupplierSyncEntry.


        :param entry_mini_app: The entry_mini_app of this PoiSupplierSyncEntry.  # noqa: E501
        :type: PoiSupplierSyncEntryResponse
        """

        self._entry_mini_app = entry_mini_app

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiSupplierSyncEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiSupplierSyncEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
