# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiSkuSyncSkus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price': 'int',
        'stock': 'int',
        'status': 'OnlineStatus',
        'attributes': 'SkuAttributes'
    }

    attribute_map = {
        'price': 'price',
        'stock': 'stock',
        'status': 'status',
        'attributes': 'attributes'
    }

    def __init__(self, price=None, stock=None, status=None, attributes=None):  # noqa: E501
        """PoiSkuSyncSkus - a model defined in Swagger"""  # noqa: E501
        self._price = None
        self._stock = None
        self._status = None
        self._attributes = None
        self.discriminator = None
        self.price = price
        self.stock = stock
        self.status = status
        self.attributes = attributes

    @property
    def price(self):
        """Gets the price of this PoiSkuSyncSkus.  # noqa: E501

        价格(人民币分)  # noqa: E501

        :return: The price of this PoiSkuSyncSkus.  # noqa: E501
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PoiSkuSyncSkus.

        价格(人民币分)  # noqa: E501

        :param price: The price of this PoiSkuSyncSkus.  # noqa: E501
        :type: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def stock(self):
        """Gets the stock of this PoiSkuSyncSkus.  # noqa: E501

        库存数量  # noqa: E501

        :return: The stock of this PoiSkuSyncSkus.  # noqa: E501
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this PoiSkuSyncSkus.

        库存数量  # noqa: E501

        :param stock: The stock of this PoiSkuSyncSkus.  # noqa: E501
        :type: int
        """
        if stock is None:
            raise ValueError("Invalid value for `stock`, must not be `None`")  # noqa: E501

        self._stock = stock

    @property
    def status(self):
        """Gets the status of this PoiSkuSyncSkus.  # noqa: E501


        :return: The status of this PoiSkuSyncSkus.  # noqa: E501
        :rtype: OnlineStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this PoiSkuSyncSkus.


        :param status: The status of this PoiSkuSyncSkus.  # noqa: E501
        :type: OnlineStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def attributes(self):
        """Gets the attributes of this PoiSkuSyncSkus.  # noqa: E501


        :return: The attributes of this PoiSkuSyncSkus.  # noqa: E501
        :rtype: SkuAttributes
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this PoiSkuSyncSkus.


        :param attributes: The attributes of this PoiSkuSyncSkus.  # noqa: E501
        :type: SkuAttributes
        """
        if attributes is None:
            raise ValueError("Invalid value for `attributes`, must not be `None`")  # noqa: E501

        self._attributes = attributes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiSkuSyncSkus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiSkuSyncSkus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
