# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiSpuQueryResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sync_status': 'SyncStatus',
        'error_code': 'ErrorCode',
        'description': 'Description'
    }

    attribute_map = {
        'sync_status': 'sync_status',
        'error_code': 'error_code',
        'description': 'description'
    }

    def __init__(self, sync_status=None, error_code=None, description=None):  # noqa: E501
        """PoiSpuQueryResponseData - a model defined in Swagger"""  # noqa: E501
        self._sync_status = None
        self._error_code = None
        self._description = None
        self.discriminator = None
        if sync_status is not None:
            self.sync_status = sync_status
        self.error_code = error_code
        self.description = description

    @property
    def sync_status(self):
        """Gets the sync_status of this PoiSpuQueryResponseData.  # noqa: E501


        :return: The sync_status of this PoiSpuQueryResponseData.  # noqa: E501
        :rtype: SyncStatus
        """
        return self._sync_status

    @sync_status.setter
    def sync_status(self, sync_status):
        """Sets the sync_status of this PoiSpuQueryResponseData.


        :param sync_status: The sync_status of this PoiSpuQueryResponseData.  # noqa: E501
        :type: SyncStatus
        """

        self._sync_status = sync_status

    @property
    def error_code(self):
        """Gets the error_code of this PoiSpuQueryResponseData.  # noqa: E501


        :return: The error_code of this PoiSpuQueryResponseData.  # noqa: E501
        :rtype: ErrorCode
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this PoiSpuQueryResponseData.


        :param error_code: The error_code of this PoiSpuQueryResponseData.  # noqa: E501
        :type: ErrorCode
        """
        if error_code is None:
            raise ValueError("Invalid value for `error_code`, must not be `None`")  # noqa: E501

        self._error_code = error_code

    @property
    def description(self):
        """Gets the description of this PoiSpuQueryResponseData.  # noqa: E501


        :return: The description of this PoiSpuQueryResponseData.  # noqa: E501
        :rtype: Description
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PoiSpuQueryResponseData.


        :param description: The description of this PoiSpuQueryResponseData.  # noqa: E501
        :type: Description
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiSpuQueryResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiSpuQueryResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
