# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiExtHotelSkuResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'spu_ext_id': 'str',
        'start_date': 'str',
        'end_date': 'str',
        'price': 'int',
        'stock': 'int'
    }

    attribute_map = {
        'spu_ext_id': 'spu_ext_id',
        'start_date': 'start_date',
        'end_date': 'end_date',
        'price': 'price',
        'stock': 'stock'
    }

    def __init__(self, spu_ext_id=None, start_date=None, end_date=None, price=None, stock=None):  # noqa: E501
        """PoiExtHotelSkuResponseData - a model defined in Swagger"""  # noqa: E501
        self._spu_ext_id = None
        self._start_date = None
        self._end_date = None
        self._price = None
        self._stock = None
        self.discriminator = None
        self.spu_ext_id = spu_ext_id
        self.start_date = start_date
        self.end_date = end_date
        self.price = price
        if stock is not None:
            self.stock = stock

    @property
    def spu_ext_id(self):
        """Gets the spu_ext_id of this PoiExtHotelSkuResponseData.  # noqa: E501

        接入方SPU ID  # noqa: E501

        :return: The spu_ext_id of this PoiExtHotelSkuResponseData.  # noqa: E501
        :rtype: str
        """
        return self._spu_ext_id

    @spu_ext_id.setter
    def spu_ext_id(self, spu_ext_id):
        """Sets the spu_ext_id of this PoiExtHotelSkuResponseData.

        接入方SPU ID  # noqa: E501

        :param spu_ext_id: The spu_ext_id of this PoiExtHotelSkuResponseData.  # noqa: E501
        :type: str
        """
        if spu_ext_id is None:
            raise ValueError("Invalid value for `spu_ext_id`, must not be `None`")  # noqa: E501

        self._spu_ext_id = spu_ext_id

    @property
    def start_date(self):
        """Gets the start_date of this PoiExtHotelSkuResponseData.  # noqa: E501

        价格时间区间[start_date, end_date)  # noqa: E501

        :return: The start_date of this PoiExtHotelSkuResponseData.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this PoiExtHotelSkuResponseData.

        价格时间区间[start_date, end_date)  # noqa: E501

        :param start_date: The start_date of this PoiExtHotelSkuResponseData.  # noqa: E501
        :type: str
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this PoiExtHotelSkuResponseData.  # noqa: E501

        价格时间区间[start_date, end_date)  # noqa: E501

        :return: The end_date of this PoiExtHotelSkuResponseData.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this PoiExtHotelSkuResponseData.

        价格时间区间[start_date, end_date)  # noqa: E501

        :param end_date: The end_date of this PoiExtHotelSkuResponseData.  # noqa: E501
        :type: str
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date

    @property
    def price(self):
        """Gets the price of this PoiExtHotelSkuResponseData.  # noqa: E501

        房型价格(人民币分)  # noqa: E501

        :return: The price of this PoiExtHotelSkuResponseData.  # noqa: E501
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PoiExtHotelSkuResponseData.

        房型价格(人民币分)  # noqa: E501

        :param price: The price of this PoiExtHotelSkuResponseData.  # noqa: E501
        :type: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def stock(self):
        """Gets the stock of this PoiExtHotelSkuResponseData.  # noqa: E501

        库存量  # noqa: E501

        :return: The stock of this PoiExtHotelSkuResponseData.  # noqa: E501
        :rtype: int
        """
        return self._stock

    @stock.setter
    def stock(self, stock):
        """Sets the stock of this PoiExtHotelSkuResponseData.

        库存量  # noqa: E501

        :param stock: The stock of this PoiExtHotelSkuResponseData.  # noqa: E501
        :type: int
        """

        self._stock = stock

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiExtHotelSkuResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiExtHotelSkuResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
