# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiSkuSyncBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'spu_ext_id': 'str',
        'skus': 'list[PoiSkuSyncSkus]'
    }

    attribute_map = {
        'spu_ext_id': 'spu_ext_id',
        'skus': 'skus'
    }

    def __init__(self, spu_ext_id=None, skus=None):  # noqa: E501
        """PoiSkuSyncBody - a model defined in Swagger"""  # noqa: E501
        self._spu_ext_id = None
        self._skus = None
        self.discriminator = None
        self.spu_ext_id = spu_ext_id
        self.skus = skus

    @property
    def spu_ext_id(self):
        """Gets the spu_ext_id of this PoiSkuSyncBody.  # noqa: E501

        外部平台SPU ID  # noqa: E501

        :return: The spu_ext_id of this PoiSkuSyncBody.  # noqa: E501
        :rtype: str
        """
        return self._spu_ext_id

    @spu_ext_id.setter
    def spu_ext_id(self, spu_ext_id):
        """Sets the spu_ext_id of this PoiSkuSyncBody.

        外部平台SPU ID  # noqa: E501

        :param spu_ext_id: The spu_ext_id of this PoiSkuSyncBody.  # noqa: E501
        :type: str
        """
        if spu_ext_id is None:
            raise ValueError("Invalid value for `spu_ext_id`, must not be `None`")  # noqa: E501

        self._spu_ext_id = spu_ext_id

    @property
    def skus(self):
        """Gets the skus of this PoiSkuSyncBody.  # noqa: E501


        :return: The skus of this PoiSkuSyncBody.  # noqa: E501
        :rtype: list[PoiSkuSyncSkus]
        """
        return self._skus

    @skus.setter
    def skus(self, skus):
        """Sets the skus of this PoiSkuSyncBody.


        :param skus: The skus of this PoiSkuSyncBody.  # noqa: E501
        :type: list[PoiSkuSyncSkus]
        """
        if skus is None:
            raise ValueError("Invalid value for `skus`, must not be `None`")  # noqa: E501

        self._skus = skus

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiSkuSyncBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiSkuSyncBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
