# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class SkuAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        '_1301': 'str'
    }

    attribute_map = {
        '_1301': '1301'
    }

    def __init__(self, _1301=None):  # noqa: E501
        """SkuAttributes - a model defined in Swagger"""  # noqa: E501
        self.__1301 = None
        self.discriminator = None
        if _1301 is not None:
            self._1301 = _1301

    @property
    def _1301(self):
        """Gets the _1301 of this SkuAttributes.  # noqa: E501

        酒店、名宿SKU日期  # noqa: E501

        :return: The _1301 of this SkuAttributes.  # noqa: E501
        :rtype: str
        """
        return self.__1301

    @_1301.setter
    def _1301(self, _1301):
        """Sets the _1301 of this SkuAttributes.

        酒店、名宿SKU日期  # noqa: E501

        :param _1301: The _1301 of this SkuAttributes.  # noqa: E501
        :type: str
        """

        self.__1301 = _1301

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SkuAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SkuAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
