# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class DevtoolMonitorCallBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scope_list': 'list[str]',
        'interface_list': 'list[str]'
    }

    attribute_map = {
        'scope_list': 'scope_list',
        'interface_list': 'interface_list'
    }

    def __init__(self, scope_list=None, interface_list=None):  # noqa: E501
        """DevtoolMonitorCallBody - a model defined in Swagger"""  # noqa: E501
        self._scope_list = None
        self._interface_list = None
        self.discriminator = None
        if scope_list is not None:
            self.scope_list = scope_list
        if interface_list is not None:
            self.interface_list = interface_list

    @property
    def scope_list(self):
        """Gets the scope_list of this DevtoolMonitorCallBody.  # noqa: E501

        scope支持批量查询  # noqa: E501

        :return: The scope_list of this DevtoolMonitorCallBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._scope_list

    @scope_list.setter
    def scope_list(self, scope_list):
        """Sets the scope_list of this DevtoolMonitorCallBody.

        scope支持批量查询  # noqa: E501

        :param scope_list: The scope_list of this DevtoolMonitorCallBody.  # noqa: E501
        :type: list[str]
        """

        self._scope_list = scope_list

    @property
    def interface_list(self):
        """Gets the interface_list of this DevtoolMonitorCallBody.  # noqa: E501

        接口支持批量查询  # noqa: E501

        :return: The interface_list of this DevtoolMonitorCallBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._interface_list

    @interface_list.setter
    def interface_list(self, interface_list):
        """Sets the interface_list of this DevtoolMonitorCallBody.

        接口支持批量查询  # noqa: E501

        :param interface_list: The interface_list of this DevtoolMonitorCallBody.  # noqa: E501
        :type: list[str]
        """

        self._interface_list = interface_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DevtoolMonitorCallBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevtoolMonitorCallBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
