# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class HotSentence(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hot_level': 'int',
        'sentence': 'str'
    }

    attribute_map = {
        'hot_level': 'hot_level',
        'sentence': 'sentence'
    }

    def __init__(self, hot_level=None, sentence=None):  # noqa: E501
        """HotSentence - a model defined in Swagger"""  # noqa: E501
        self._hot_level = None
        self._sentence = None
        self.discriminator = None
        self.hot_level = hot_level
        self.sentence = sentence

    @property
    def hot_level(self):
        """Gets the hot_level of this HotSentence.  # noqa: E501

        热度 综合点赞、评论、转发等计算得出  # noqa: E501

        :return: The hot_level of this HotSentence.  # noqa: E501
        :rtype: int
        """
        return self._hot_level

    @hot_level.setter
    def hot_level(self, hot_level):
        """Sets the hot_level of this HotSentence.

        热度 综合点赞、评论、转发等计算得出  # noqa: E501

        :param hot_level: The hot_level of this HotSentence.  # noqa: E501
        :type: int
        """
        if hot_level is None:
            raise ValueError("Invalid value for `hot_level`, must not be `None`")  # noqa: E501

        self._hot_level = hot_level

    @property
    def sentence(self):
        """Gets the sentence of this HotSentence.  # noqa: E501

        热点词  # noqa: E501

        :return: The sentence of this HotSentence.  # noqa: E501
        :rtype: str
        """
        return self._sentence

    @sentence.setter
    def sentence(self, sentence):
        """Sets the sentence of this HotSentence.

        热点词  # noqa: E501

        :param sentence: The sentence of this HotSentence.  # noqa: E501
        :type: str
        """
        if sentence is None:
            raise ValueError("Invalid value for `sentence`, must not be `None`")  # noqa: E501

        self._sentence = sentence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HotSentence, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HotSentence):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
