# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class ExtShopInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shop_id': 'str',
        'ext_shop_id': 'str'
    }

    attribute_map = {
        'shop_id': 'shop_id',
        'ext_shop_id': 'ext_shop_id'
    }

    def __init__(self, shop_id=None, ext_shop_id=None):  # noqa: E501
        """ExtShopInfo - a model defined in Swagger"""  # noqa: E501
        self._shop_id = None
        self._ext_shop_id = None
        self.discriminator = None
        if shop_id is not None:
            self.shop_id = shop_id
        self.ext_shop_id = ext_shop_id

    @property
    def shop_id(self):
        """Gets the shop_id of this ExtShopInfo.  # noqa: E501

        抖音商户ID  # noqa: E501

        :return: The shop_id of this ExtShopInfo.  # noqa: E501
        :rtype: str
        """
        return self._shop_id

    @shop_id.setter
    def shop_id(self, shop_id):
        """Sets the shop_id of this ExtShopInfo.

        抖音商户ID  # noqa: E501

        :param shop_id: The shop_id of this ExtShopInfo.  # noqa: E501
        :type: str
        """

        self._shop_id = shop_id

    @property
    def ext_shop_id(self):
        """Gets the ext_shop_id of this ExtShopInfo.  # noqa: E501

        外部商户ID  # noqa: E501

        :return: The ext_shop_id of this ExtShopInfo.  # noqa: E501
        :rtype: str
        """
        return self._ext_shop_id

    @ext_shop_id.setter
    def ext_shop_id(self, ext_shop_id):
        """Sets the ext_shop_id of this ExtShopInfo.

        外部商户ID  # noqa: E501

        :param ext_shop_id: The ext_shop_id of this ExtShopInfo.  # noqa: E501
        :type: str
        """
        if ext_shop_id is None:
            raise ValueError("Invalid value for `ext_shop_id`, must not be `None`")  # noqa: E501

        self._ext_shop_id = ext_shop_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExtShopInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExtShopInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
