# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class PoiOrderSyncBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mini_app': 'PoiOrderSyncResponse',
        'order_type': 'int',
        'date_time': 'int',
        'order_detail': 'str',
        'ext_shop_info': 'ExtShopInfo'
    }

    attribute_map = {
        'mini_app': 'mini_app',
        'order_type': 'order_type',
        'date_time': 'date_time',
        'order_detail': 'order_detail',
        'ext_shop_info': 'ext_shop_info'
    }

    def __init__(self, mini_app=None, order_type=None, date_time=None, order_detail=None, ext_shop_info=None):  # noqa: E501
        """PoiOrderSyncBody - a model defined in Swagger"""  # noqa: E501
        self._mini_app = None
        self._order_type = None
        self._date_time = None
        self._order_detail = None
        self._ext_shop_info = None
        self.discriminator = None
        if mini_app is not None:
            self.mini_app = mini_app
        self.order_type = order_type
        self.date_time = date_time
        self.order_detail = order_detail
        self.ext_shop_info = ext_shop_info

    @property
    def mini_app(self):
        """Gets the mini_app of this PoiOrderSyncBody.  # noqa: E501


        :return: The mini_app of this PoiOrderSyncBody.  # noqa: E501
        :rtype: PoiOrderSyncResponse
        """
        return self._mini_app

    @mini_app.setter
    def mini_app(self, mini_app):
        """Sets the mini_app of this PoiOrderSyncBody.


        :param mini_app: The mini_app of this PoiOrderSyncBody.  # noqa: E501
        :type: PoiOrderSyncResponse
        """

        self._mini_app = mini_app

    @property
    def order_type(self):
        """Gets the order_type of this PoiOrderSyncBody.  # noqa: E501

        订单类型- 201 预约点餐订单, 202 餐厅预定订单, 203 餐厅排队订单, 9001 景区门票订单, 9101 团购券订单  # noqa: E501

        :return: The order_type of this PoiOrderSyncBody.  # noqa: E501
        :rtype: int
        """
        return self._order_type

    @order_type.setter
    def order_type(self, order_type):
        """Sets the order_type of this PoiOrderSyncBody.

        订单类型- 201 预约点餐订单, 202 餐厅预定订单, 203 餐厅排队订单, 9001 景区门票订单, 9101 团购券订单  # noqa: E501

        :param order_type: The order_type of this PoiOrderSyncBody.  # noqa: E501
        :type: int
        """
        if order_type is None:
            raise ValueError("Invalid value for `order_type`, must not be `None`")  # noqa: E501
        allowed_values = [201, 202, 203, 9001, 9101]  # noqa: E501
        if order_type not in allowed_values:
            raise ValueError(
                "Invalid value for `order_type` ({0}), must be one of {1}"  # noqa: E501
                .format(order_type, allowed_values)
            )

        self._order_type = order_type

    @property
    def date_time(self):
        """Gets the date_time of this PoiOrderSyncBody.  # noqa: E501

        发送请求的时间，精确到毫秒  # noqa: E501

        :return: The date_time of this PoiOrderSyncBody.  # noqa: E501
        :rtype: int
        """
        return self._date_time

    @date_time.setter
    def date_time(self, date_time):
        """Sets the date_time of this PoiOrderSyncBody.

        发送请求的时间，精确到毫秒  # noqa: E501

        :param date_time: The date_time of this PoiOrderSyncBody.  # noqa: E501
        :type: int
        """
        if date_time is None:
            raise ValueError("Invalid value for `date_time`, must not be `None`")  # noqa: E501

        self._date_time = date_time

    @property
    def order_detail(self):
        """Gets the order_detail of this PoiOrderSyncBody.  # noqa: E501

        订单的细节，不同的订单业务有不同的结构体，请具体询问业务方字段结构  # noqa: E501

        :return: The order_detail of this PoiOrderSyncBody.  # noqa: E501
        :rtype: str
        """
        return self._order_detail

    @order_detail.setter
    def order_detail(self, order_detail):
        """Sets the order_detail of this PoiOrderSyncBody.

        订单的细节，不同的订单业务有不同的结构体，请具体询问业务方字段结构  # noqa: E501

        :param order_detail: The order_detail of this PoiOrderSyncBody.  # noqa: E501
        :type: str
        """
        if order_detail is None:
            raise ValueError("Invalid value for `order_detail`, must not be `None`")  # noqa: E501

        self._order_detail = order_detail

    @property
    def ext_shop_info(self):
        """Gets the ext_shop_info of this PoiOrderSyncBody.  # noqa: E501


        :return: The ext_shop_info of this PoiOrderSyncBody.  # noqa: E501
        :rtype: ExtShopInfo
        """
        return self._ext_shop_info

    @ext_shop_info.setter
    def ext_shop_info(self, ext_shop_info):
        """Sets the ext_shop_info of this PoiOrderSyncBody.


        :param ext_shop_info: The ext_shop_info of this PoiOrderSyncBody.  # noqa: E501
        :type: ExtShopInfo
        """
        if ext_shop_info is None:
            raise ValueError("Invalid value for `ext_shop_info`, must not be `None`")  # noqa: E501

        self._ext_shop_info = ext_shop_info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PoiOrderSyncBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PoiOrderSyncBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
