# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

import pprint
import re  # noqa: F401

import six


class ToutiaoVideoCreateBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'video_id': 'str',
        'text': 'str'
    }

    attribute_map = {
        'video_id': 'video_id',
        'text': 'text'
    }

    def __init__(self, video_id=None, text=None):  # noqa: E501
        """ToutiaoVideoCreateBody - a model defined in Swagger"""  # noqa: E501
        self._video_id = None
        self._text = None
        self.discriminator = None
        self.video_id = video_id
        if text is not None:
            self.text = text

    @property
    def video_id(self):
        """Gets the video_id of this ToutiaoVideoCreateBody.  # noqa: E501

        video_id, 通过/toutiao/video/upload/接口得到  # noqa: E501

        :return: The video_id of this ToutiaoVideoCreateBody.  # noqa: E501
        :rtype: str
        """
        return self._video_id

    @video_id.setter
    def video_id(self, video_id):
        """Sets the video_id of this ToutiaoVideoCreateBody.

        video_id, 通过/toutiao/video/upload/接口得到  # noqa: E501

        :param video_id: The video_id of this ToutiaoVideoCreateBody.  # noqa: E501
        :type: str
        """
        if video_id is None:
            raise ValueError("Invalid value for `video_id`, must not be `None`")  # noqa: E501

        self._video_id = video_id

    @property
    def text(self):
        """Gets the text of this ToutiaoVideoCreateBody.  # noqa: E501

        视频标题不要超过30个字符  # noqa: E501

        :return: The text of this ToutiaoVideoCreateBody.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ToutiaoVideoCreateBody.

        视频标题不要超过30个字符  # noqa: E501

        :param text: The text of this ToutiaoVideoCreateBody.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ToutiaoVideoCreateBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ToutiaoVideoCreateBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
