# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import re

# python 2 and python 3 compatibility library
import six

from douyin.open.share_id.api_client import ApiClient


class ShareIdApi(object):
    """NOTE: 由抖音小开自动生成，请勿自己修改
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def share_id_get(self, access_token, **kwargs):
        """获取share-id

        * Scope: `aweme.share` 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.share_id_get(access_token, async_req=False)
        >>> result = thread.get()

        :param async_req bool
        :param str access_token: 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
        :param bool need_callback:
        :param str source_style_id: 多来源样式id（暂未开放）
        :param str default_hashtag: 追踪分享默认hashtag
        :param str link_param: 分享来源url附加参数（暂未开放）
        :return: ShareidResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.share_id_get_with_http_info(access_token, **kwargs)
        else:
            (data) = self.share_id_get_with_http_info(access_token, **kwargs)
            return data

    def share_id_get_with_http_info(self, access_token, **kwargs):
        """获取share-id  # noqa: E501

        * Scope: `aweme.share` 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.share_id_get_with_http_info(access_token, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str access_token: 调用/oauth/client_token/生成的token，此token不需要用户授权。 (required)
        :param bool need_callback:
        :param str source_style_id: 多来源样式id（暂未开放）
        :param str default_hashtag: 追踪分享默认hashtag
        :param str link_param: 分享来源url附加参数（暂未开放）
        :return: ShareidResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['access_token', 'need_callback', 'source_style_id', 'default_hashtag', 'link_param']
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method share_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'access_token' is set
        if ('access_token' not in params or
                params['access_token'] is None):
            raise ValueError("Missing the required parameter `access_token` when calling `share_id_get`")

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'access_token' in params:
            query_params.append(('access_token', params['access_token']))
        if 'need_callback' in params:
            query_params.append(('need_callback', params['need_callback']))
        if 'source_style_id' in params:
            query_params.append(('source_style_id', params['source_style_id']))
        if 'default_hashtag' in params:
            query_params.append(('default_hashtag', params['default_hashtag']))
        if 'link_param' in params:
            query_params.append(('link_param', params['link_param']))

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(
            '/share-id/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ShareidResponse',
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
