# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.media_upload.api.media_upload_api import MediaUploadApi
from douyin.open.media_upload.rest import ApiException

from douyin.open.media_upload.model.media_upload_response import MediaUploadResponse


class TestMediaUploadApi(unittest.TestCase):
    """MediaUploadApi unit test stubs"""

    def setUp(self):
        self.api = MediaUploadApi()

    def tearDown(self):
        pass

    def test_media_upload_post(self):
        """Test case for media_upload_post

        上传素材
        """
        
        resp = self.api.media_upload_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', media='media_example')
        pass


if __name__ == '__main__':
    unittest.main()
