# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.video_comment.api.video_comment_api import VideoCommentApi
from douyin.open.video_comment.rest import ApiException

from douyin.open.video_comment.model.common_response import CommonResponse
from douyin.open.video_comment.model.video_comment_list_response import VideoCommentListResponse
from douyin.open.video_comment.model.video_comment_reply_body import VideoCommentReplyBody
from douyin.open.video_comment.model.video_comment_top_body import VideoCommentTopBody


class TestVideoCommentApi(unittest.TestCase):
    """VideoCommentApi unit test stubs"""

    def setUp(self):
        self.api = VideoCommentApi()

    def tearDown(self):
        pass

    def test_video_comment_list_get(self):
        """Test case for video_comment_list_get

        评论列表
        """
        
        resp = self.api.video_comment_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=0, count=10, item_id='item_id_example', )
        pass

    def test_video_comment_reply_list_get(self):
        """Test case for video_comment_reply_list_get

        评论回复列表
        """
        
        resp = self.api.video_comment_reply_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=0, count=10, item_id='item_id_example', comment_id='comment_id_example', )
        pass

    def test_video_comment_reply_post(self):
        """Test case for video_comment_reply_post

        回复视频评论
        """
        body=VideoCommentReplyBody()
        resp = self.api.video_comment_reply_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_video_comment_top_post(self):
        """Test case for video_comment_top_post

        置顶视频评论(企业号)
        """
        body=VideoCommentTopBody()
        resp = self.api.video_comment_top_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass


if __name__ == '__main__':
    unittest.main()
