# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.toutiao.video.create.api.toutiao_video_publish_api import ToutiaoVideoPublishApi
from douyin.open.toutiao.video.create.rest import ApiException

from douyin.open.toutiao.video.create.model.toutiao_video_create_body import ToutiaoVideoCreateBody
from douyin.open.toutiao.video.create.model.toutiao_video_create_response import ToutiaoVideoCreateResponse
from douyin.open.toutiao.video.create.model.toutiao_video_upload_response import ToutiaoVideoUploadResponse


class TestToutiaoVideoPublishApi(unittest.TestCase):
    """ToutiaoVideoPublishApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoVideoPublishApi()

    def tearDown(self):
        pass

    def test_toutiao_video_create_post(self):
        """Test case for toutiao_video_create_post

        创建头条视频  注意：重复的video_id不会生成新的视频
        """
        body=ToutiaoVideoCreateBody()
        resp = self.api.toutiao_video_create_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_toutiao_video_upload_post(self):
        """Test case for toutiao_video_upload_post

        上传视频到文件服务器
        """
        
        resp = self.api.toutiao_video_upload_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', video='video_example')
        pass


if __name__ == '__main__':
    unittest.main()
