# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.user.following.api.following_list_api import FollowingListApi
from douyin.open.user.following.rest import ApiException

from douyin.open.user.following.model.following_list_response import FollowingListResponse


class TestFollowingListApi(unittest.TestCase):
    """FollowingListApi unit test stubs"""

    def setUp(self):
        self.api = FollowingListApi()

    def tearDown(self):
        pass

    def test_following_list_get(self):
        """Test case for following_list_get

        获取关注列表
        """
        
        resp = self.api.following_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=0, count=10, )
        pass


if __name__ == '__main__':
    unittest.main()
