# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.image_create.api.image_api import ImageApi
from douyin.open.image_create.rest import ApiException

from douyin.open.image_create.model.image_create_body import ImageCreateBody
from douyin.open.image_create.model.image_create_response import ImageCreateResponse
from douyin.open.image_create.model.image_upload_response import ImageUploadResponse


class TestImageApi(unittest.TestCase):
    """ImageApi unit test stubs"""

    def setUp(self):
        self.api = ImageApi()

    def tearDown(self):
        pass

    def test_image_create_post(self):
        """Test case for image_create_post

        发布图片
        """
        body=ImageCreateBody()
        resp = self.api.image_create_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_image_upload_post(self):
        """Test case for image_upload_post

        上传图片到文件服务器
        """
        
        resp = self.api.image_upload_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', image='image_example')
        pass


if __name__ == '__main__':
    unittest.main()
