# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.toutiao.video.list.api.toutiao_video_list_api import ToutiaoVideoListApi
from douyin.open.toutiao.video.list.rest import ApiException

from douyin.open.toutiao.video.list.model.toutiao_video_list_response import ToutiaoVideoListResponse


class TestToutiaoVideoListApi(unittest.TestCase):
    """ToutiaoVideoListApi unit test stubs"""

    def setUp(self):
        self.api = ToutiaoVideoListApi()

    def tearDown(self):
        pass

    def test_toutiao_video_list_get(self):
        """Test case for toutiao_video_list_get

        获取用户已发布的视频，支持分页
        """
        
        resp = self.api.toutiao_video_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=0, count=10, )
        pass


if __name__ == '__main__':
    unittest.main()
