# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.poi.product.api.poi_spu_api import PoiSpuApi
from douyin.open.poi.product.rest import ApiException

from douyin.open.poi.product.model.poi_sku_sync_body import PoiSkuSyncBody
from douyin.open.poi.product.model.poi_sku_sync_response import PoiSkuSyncResponse
from douyin.open.poi.product.model.poi_spu_query_response import PoiSpuQueryResponse
from douyin.open.poi.product.model.poi_spu_sync_body import PoiSpuSyncBody
from douyin.open.poi.product.model.poi_spu_sync_response import PoiSpuSyncResponse


class TestPoiSpuApi(unittest.TestCase):
    """PoiSpuApi unit test stubs"""

    def setUp(self):
        self.api = PoiSpuApi()

    def tearDown(self):
        pass

    def test_poi_sku_sync_post(self):
        """Test case for poi_sku_sync_post

        SKU同步
        """
        body=PoiSkuSyncBody()
        resp = self.api.poi_sku_sync_post(access_token='clt.943da17996fb5cebfbc70c044c3fc25a57T54DcjT6HNKGqnUdxzy1KcxFnZ', body=body)
        pass

    def test_poi_spu_query_get(self):
        """Test case for poi_spu_query_get

        查询SPU
        """
        
        resp = self.api.poi_spu_query_get(access_token='clt.943da17996fb5cebfbc70c044c3fc25a57T54DcjT6HNKGqnUdxzy1KcxFnZ', spu_ext_id='spu_ext_id_example', )
        pass

    def test_poi_spu_sync_post(self):
        """Test case for poi_spu_sync_post

        SPU同步
        """
        body=PoiSpuSyncBody()
        resp = self.api.poi_spu_sync_post(access_token='clt.943da17996fb5cebfbc70c044c3fc25a57T54DcjT6HNKGqnUdxzy1KcxFnZ', body=body)
        pass


if __name__ == '__main__':
    unittest.main()
