# coding: utf-8

"""
    企业号意向用户管理

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.enterprise_leads.api.enterprise_leads_api import EnterpriseLeadsApi
from douyin.open.enterprise_leads.rest import ApiException

from douyin.open.enterprise_leads.model.enterprise_leads_tag_create_body import EnterpriseLeadsTagCreateBody
from douyin.open.enterprise_leads.model.enterprise_leads_tag_create_response import EnterpriseLeadsTagCreateResponse
from douyin.open.enterprise_leads.model.enterprise_leads_tag_delete_body import EnterpriseLeadsTagDeleteBody
from douyin.open.enterprise_leads.model.enterprise_leads_tag_delete_response import EnterpriseLeadsTagDeleteResponse
from douyin.open.enterprise_leads.model.enterprise_leads_tag_list_response import EnterpriseLeadsTagListResponse
from douyin.open.enterprise_leads.model.enterprise_leads_tag_update_body import EnterpriseLeadsTagUpdateBody
from douyin.open.enterprise_leads.model.enterprise_leads_tag_user_list_response import EnterpriseLeadsTagUserListResponse
from douyin.open.enterprise_leads.model.enterprise_leads_tag_user_update_body import EnterpriseLeadsTagUserUpdateBody
from douyin.open.enterprise_leads.model.enterprise_leads_user_action_list_response import EnterpriseLeadsUserActionListResponse
from douyin.open.enterprise_leads.model.enterprise_leads_user_detail_response import EnterpriseLeadsUserDetailResponse
from douyin.open.enterprise_leads.model.enterprise_leads_user_list_response import EnterpriseLeadsUserListResponse


class TestEnterpriseLeadsApi(unittest.TestCase):
    """EnterpriseLeadsApi unit test stubs"""

    def setUp(self):
        self.api = EnterpriseLeadsApi()

    def tearDown(self):
        pass

    def test_enterprise_leads_tag_create_post(self):
        """Test case for enterprise_leads_tag_create_post

        创建标签
        """
        body=EnterpriseLeadsTagCreateBody()
        resp = self.api.enterprise_leads_tag_create_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_enterprise_leads_tag_delete_post(self):
        """Test case for enterprise_leads_tag_delete_post

        删除标签
        """
        body=EnterpriseLeadsTagDeleteBody()
        resp = self.api.enterprise_leads_tag_delete_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_enterprise_leads_tag_list_get(self):
        """Test case for enterprise_leads_tag_list_get

        获取标签列表
        """
        
        resp = self.api.enterprise_leads_tag_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=56, count=10, )
        pass

    def test_enterprise_leads_tag_update_post(self):
        """Test case for enterprise_leads_tag_update_post

        编辑标签
        """
        body=EnterpriseLeadsTagUpdateBody()
        resp = self.api.enterprise_leads_tag_update_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_enterprise_leads_tag_user_list_get(self):
        """Test case for enterprise_leads_tag_user_list_get

        获取打标签的用户列表
        """
        
        resp = self.api.enterprise_leads_tag_user_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=56, count=10, tag_id=56, )
        pass

    def test_enterprise_leads_tag_user_update_post(self):
        """Test case for enterprise_leads_tag_user_update_post

        给用户设置标签
        """
        body=EnterpriseLeadsTagUserUpdateBody()
        resp = self.api.enterprise_leads_tag_user_update_post(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', body=body)
        pass

    def test_enterprise_leads_user_action_list_get(self):
        """Test case for enterprise_leads_user_action_list_get

        获取意向用户互动记录
        """
        
        resp = self.api.enterprise_leads_user_action_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', count=10, cursor='cursor_example', user_id='user_id_example', action_type=56, )
        pass

    def test_enterprise_leads_user_detail_get(self):
        """Test case for enterprise_leads_user_detail_get

        获取意向用户详情
        """
        
        resp = self.api.enterprise_leads_user_detail_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', user_id='user_id_example', )
        pass

    def test_enterprise_leads_user_list_get(self):
        """Test case for enterprise_leads_user_list_get

        获取意向用户列表
        """
        
        resp = self.api.enterprise_leads_user_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=56, count=10, start_time=56, end_time=56, leads_level=56, action_type=56, )
        pass


if __name__ == '__main__':
    unittest.main()
