# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.poi.product.api.poi_sku_api import PoiSkuApi
from douyin.open.poi.product.rest import ApiException

from douyin.open.poi.product.model.poi_ext_hotel_sku_response import PoiExtHotelSkuResponse


class TestPoiSkuApi(unittest.TestCase):
    """PoiSkuApi unit test stubs"""

    def setUp(self):
        self.api = PoiSkuApi()

    def tearDown(self):
        pass

    def test_poi_ext_hotel_sku_get(self):
        """Test case for poi_ext_hotel_sku_get

        sku拉取(该接口由接入方实现)
        """
        
        resp = self.api.poi_ext_hotel_sku_get(spu_ext_id=['[\"y0001\",\"y0002\"]'], start_date='20191001', end_date='20191007', )
        pass


if __name__ == '__main__':
    unittest.main()
