# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.share_id.api.share_id_api import ShareIdApi
from douyin.open.share_id.rest import ApiException

from douyin.open.share_id.model.shareid_response import ShareidResponse


class TestShareIdApi(unittest.TestCase):
    """ShareIdApi unit test stubs"""

    def setUp(self):
        self.api = ShareIdApi()

    def tearDown(self):
        pass

    def test_share_id_get(self):
        """Test case for share_id_get

        获取share-id
        """
        
        resp = self.api.share_id_get(access_token='clt.943da17996fb5cebfbc70c044c3fc25a57T54DcjT6HNKGqnUdxzy1KcxFnZ', need_callback=True, source_style_id='source_style_id_example', default_hashtag='default_hashtag_example', link_param='link_param_example', )
        pass


if __name__ == '__main__':
    unittest.main()
