# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    
"""

from __future__ import absolute_import

import unittest

from douyin.open.video_list.api.video_list_api import VideoListApi
from douyin.open.video_list.rest import ApiException

from douyin.open.video_list.model.video_list_response import VideoListResponse


class TestVideoListApi(unittest.TestCase):
    """VideoListApi unit test stubs"""

    def setUp(self):
        self.api = VideoListApi()

    def tearDown(self):
        pass

    def test_video_list_get(self):
        """Test case for video_list_get

        列出已发布的视频
        """
        
        resp = self.api.video_list_get(open_id='ba253642-0590-40bc-9bdf-9a1334b94059', access_token='act.1d1021d2aee3d41fee2d2add43456badMFZnrhFhfWotu3Ecuiuka27L56lr', cursor=0, count=10, )
        pass


if __name__ == '__main__':
    unittest.main()
